// <auto-generated />
namespace auction.DAL.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class V_2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(V_2));
        
        string IMigrationMetadata.Id
        {
            get { return "201809181324222_V_2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
